name = "lapce-material-icon-theme"
display-name = "Material Icon Theme"
icon = "logo.png"
version = "1.0.0"
author = "Reokodoku"
description = "A fork of vscode-material-icon-theme that can be used for Lapce"
icon-themes = ["material.toml"]
repository = "https://github.com/Reokodoku/lapce-material-icon-theme"
